# Generated by Django 2.1 on 2019-04-19 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internet_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, null=True, verbose_name='中文模块名')),
                ('unique_id', models.IntegerField()),
                ('english_name', models.CharField(max_length=55, null=True, verbose_name='英文模块名')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='每次更新时间')),
            ],
            options={
                'verbose_name': '功能模块表',
                'db_table': 'internet_module',
            },
        ),
        migrations.CreateModel(
            name='User_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Internet_Module', verbose_name='关联功能模块表')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户表外键')),
            ],
            options={
                'verbose_name': '用户功能配置表',
                'db_table': 'user_module',
            },
        ),
    ]
