# Generated by Django 2.1 on 2019-04-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_internet_module_user_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot_Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=25, null=True, verbose_name='排名')),
                ('keyword', models.CharField(max_length=55, null=True, verbose_name='关键词')),
                ('keyword_link', models.CharField(max_length=255, null=True, verbose_name='关键词链接')),
                ('news_link', models.CharField(max_length=255, null=True, verbose_name='新闻链接')),
                ('video_link', models.CharField(max_length=255, null=True, verbose_name='视频链接')),
                ('image_link', models.CharField(max_length=255, null=True, verbose_name='图片链接')),
                ('search_score', models.CharField(max_length=255, null=True, verbose_name='搜索指数')),
            ],
            options={
                'verbose_name': '每日热点表',
                'db_table': 'hot_daily',
            },
        ),
    ]
