# Generated by Django 2.1 on 2019-04-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_hot_daily_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot_daily',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
