# Generated by Django 2.1 on 2019-05-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190422_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(max_length=25, null=True, verbose_name='用户的手机号码'),
        ),
    ]
